CREATE TABLE EMPRESA(
id_empresa INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
cnpj VARCHAR(14) NOT NULL,
nome_empresa VARCHAR(80) NOT NULL,
endereco VARCHAR(120) NOT NULL,
I_E VARCHAR(12) NOT NULL
);

CREATE TABLE CARGO(
id_cargo INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
nome_cargo VARCHAR(80) NOT NULL
);

CREATE TABLE PESSOA(
id_pessoa INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
id_empresa INT UNSIGNED NOT NULL,
id_cargo INT UNSIGNED NOT NULL,
cpf VARCHAR(11) NOT NULL,
nome_pessoa VARCHAR(80) NOT NULL,
endereco VARCHAR(120) NOT NULL,
telefone VARCHAR(14) NOT NULL,
data_admissao DATE NOT NULL,
salario DECIMAL(7,2) NOT NULL,
CONSTRAINT EMPRESA_FK FOREIGN KEY (id_empresa) REFERENCES EMPRESA (id_empresa),
CONSTRAINT CARGO_FK FOREIGN KEY (id_cargo) REFERENCES CARGO(id_cargo)
);

CREATE TABLE REGISTRO_PONTO(
id_registro_ponto INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
id_pessoa INT UNSIGNED NOT NULL,
data_hora_entrada DATETIME NOT NULL,
data_hora_saida DATETIME,
CONSTRAINT PESSOA_FK FOREIGN KEY (id_pessoa) REFERENCES PESSOA (id_pessoa)
);

